using micro_system_service.Data;
using micro_system_service.Routes;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddScoped<EventsContext>(); //Injetando a conexão com o banco de dados 

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.EventRoutes(); //chamndo todo o conteúdo da event routes 


app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
